@baseUrl=http://localhost:3000/api/v1

# @name  createAccount
POST {{baseUrl}}/accounts HTTP/1.1
content-type: application/json

{
    "tax_id": "74553007002",
    "name": "John Doe",
    "email": "email@email.com",
    "monthly_income": 1000000,
    "annual_revenue": 12000000,
    "balance": 1000000
}

###
  @accountId = {{createAccount.response.body.account_id}}
###
 
# @name  getAccountById
GET {{baseUrl}}/accounts/{{accountId}} HTTP/1.1

###