// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: accounts.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const accountDeposit = `-- name: AccountDeposit :one
UPDATE accounts SET balance = balance + $1 
WHERE id = $2 RETURNING balance
`

type AccountDepositParams struct {
	Balance int64     `json:"balance"`
	ID      uuid.UUID `json:"id"`
}

func (q *Queries) AccountDeposit(ctx context.Context, arg AccountDepositParams) (int64, error) {
	row := q.db.QueryRow(ctx, accountDeposit, arg.Balance, arg.ID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const accountWithdraw = `-- name: AccountWithdraw :one
UPDATE accounts SET balance = balance - $1 
WHERE id = $2 RETURNING balance
`

type AccountWithdrawParams struct {
	Balance int64     `json:"balance"`
	ID      uuid.UUID `json:"id"`
}

func (q *Queries) AccountWithdraw(ctx context.Context, arg AccountWithdrawParams) (int64, error) {
	row := q.db.QueryRow(ctx, accountWithdraw, arg.Balance, arg.ID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (tax_id, name, monthly_income, annual_revenue, email, balance) 
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id
`

type CreateAccountParams struct {
	TaxID         string      `json:"tax_id"`
	Name          string      `json:"name"`
	MonthlyIncome pgtype.Int8 `json:"monthly_income"`
	AnnualRevenue pgtype.Int8 `json:"annual_revenue"`
	Email         string      `json:"email"`
	Balance       int64       `json:"balance"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.TaxID,
		arg.Name,
		arg.MonthlyIncome,
		arg.AnnualRevenue,
		arg.Email,
		arg.Balance,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const delete = `-- name: Delete :one
UPDATE accounts SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 RETURNING id
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, delete, id)
	err := row.Scan(&id)
	return id, err
}

const getAccountBalanceById = `-- name: GetAccountBalanceById :one
SELECT balance FROM accounts 
WHERE id = $1
`

func (q *Queries) GetAccountBalanceById(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getAccountBalanceById, id)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const getAccountById = `-- name: GetAccountById :one
SELECT id, tax_id, name, monthly_income, annual_revenue, email, balance, created_at, updated_at, deleted_at FROM accounts 
WHERE id = $1
`

func (q *Queries) GetAccountById(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountById, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.TaxID,
		&i.Name,
		&i.MonthlyIncome,
		&i.AnnualRevenue,
		&i.Email,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
