// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package pgstore

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID            uuid.UUID          `json:"id"`
	TaxID         string             `json:"tax_id"`
	Name          string             `json:"name"`
	MonthlyIncome pgtype.Int8        `json:"monthly_income"`
	AnnualRevenue pgtype.Int8        `json:"annual_revenue"`
	Email         string             `json:"email"`
	Balance       int64              `json:"balance"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}
